id: P010333
initial_creation_type: ocr
source_metadata:
  id: bdr:W23648
  title: ལམ་འབྲས་ཚོགས་བཤད
  author: ''
  volumes:
    831febd96abe4eab9a9d1693dc3b2a71:
      image_group_id: I2340
      title: ''
      volume_number: 1
      total_pages: 588
      base_file: v001.txt
    24899ccda5344c81aef96c2de0d93fc4:
      image_group_id: I2341
      title: ''
      volume_number: 2
      total_pages: 636
      base_file: v002.txt
    2a949e92d52349ff9cd2c9995797176e:
      image_group_id: I2342
      title: ''
      volume_number: 3
      total_pages: 602
      base_file: v003.txt
    47a5587065254605b44ba3367e5e4fc6:
      image_group_id: I2343
      title: ''
      volume_number: 4
      total_pages: 664
      base_file: v004.txt
    7750e73e25ad4a5c9f60ea76bbd9e0bf:
      image_group_id: I2344
      title: ''
      volume_number: 5
      total_pages: 592
      base_file: v005.txt
    0a5bcc24ce48413f8a93e75b85781394:
      image_group_id: I2345
      title: ''
      volume_number: 6
      total_pages: 640
      base_file: v006.txt
