id: I3C1A26AA
legacy_id: P010333
ocr_import_info:
  bdrc_scan_id: W23648
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T17:59:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:29:13.481524+00:00'
last_modified: 2022-09-02 09:34:32.779911
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23648
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23648
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་འབྲས་ཚོགས་བཤད།
statistics:
  ocr_word_mean_confidence_index: 0.7877250582324012
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I2340:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2340
      total_pages: 588
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2340.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7627250381613697
    legacy_id: v001
  I2345:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2345
      total_pages: 640
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2345.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8139936106644081
    legacy_id: v006
  I2341:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2341
      total_pages: 636
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2341.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7881286554490763
    legacy_id: v002
  I2342:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2342
      total_pages: 602
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2342.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7379059336401896
    legacy_id: v003
  I2344:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2344
      total_pages: 592
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2344.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.796699611211677
    legacy_id: v005
  I2343:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2343
      total_pages: 664
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2343.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8336595768261175
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
