id: I3C1A26AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:04:34+00:00'
last_modified: '2022-06-08T12:49:11.162466+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23648
  title: ལམ་འབྲས་ཚོགས་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D8AE:
      image_group_id: I2340
      title: ''
      total_pages: 588
      order: 1
      base_file: D8AE.txt
    543D:
      image_group_id: I2341
      title: ''
      total_pages: 636
      order: 2
      base_file: 543D.txt
    '8794':
      image_group_id: I2342
      title: ''
      total_pages: 602
      order: 3
      base_file: 8794.txt
    7A8C:
      image_group_id: I2343
      title: ''
      total_pages: 664
      order: 4
      base_file: 7A8C.txt
    '2544':
      image_group_id: I2344
      title: ''
      total_pages: 592
      order: 5
      base_file: 2544.txt
    B336:
      image_group_id: I2345
      title: ''
      total_pages: 640
      order: 6
      base_file: B336.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
